### ISSUE TITLE
Glu package In Debian/Ubuntu repositories

### ISSUE THREAD

**Issue by github-userx** [jorio/Nanosaur#15]
for building on linux you mention glu as a requirement. We could add to the BUILD.md that on Ubuntu/Debian it’s the Package: freeglut3-dev

Or is this a dumb/wrong idea?

**Comment by jorio** [comment]
It's absolutely not a dumb idea!

I was planning on doing away with the glu dependency, as I did with Bugdom, because the game only needs two functions from it that can easily be reimplemented. But we can certainly complete the build documentation with the name of the Debian package in the meantime.

**Comment by jorio** [comment]
Closing this because I removed the dependency on glu (b567a3e).
