### ISSUE TITLE
Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by foote-darrell** [jorio/Nanosaur#31]
I followed the exact steps in bulding the game. It seems that the instructions do not mention changing the directory to the _Nanosaur_ folder after the first step, so I did took the inference to try that. Is this the intended folder for the next step? It shoud be specified in the instructions. 

I did change the directory to _Nanosaur_ where the CMakeLists.txt file actually is. [It just then reports "Configuring incomplete, errors occurred!"](https://pastebin.com/24tR3tL8). How ought I resolve this?

**Comment by foote-darrell** [comment]
I did extract the SDL2-devel-2.0.22-VC.zip into the **extern** folder. It didn't really say wheather to include the SLD2-devel folder itself, so I placed the files directly in the **extern** folder. Is this the intended method? ![image](https://user-images.githubusercontent.com/70550621/202934136-40623e30-8c7c-4cae-a3d3-2ec5f04073eb.png)

**Comment by jorio** [comment]
After extracting SDL2-devel-2.0.22-VC.zip, you should keep the "SDL2-2.0.22" directory and move it to "extern". So, in order to set up the game for Visual Studio, "extern" should contain two directories:
- Pomme
- SDL2-2.0.22

Alternatively, you can install Python 3 and run `python3 build.py` which will run all these steps for you.

**Comment by foote-darrell** [comment]
It got it to work. I was wanting to compile the game with [the render distance modified.](https://www.youtube.com/watch?v=ngrADKFARKA). The steps should say to `cd Nanosaur` becuase it is only imppied to do this.
