### ISSUE TITLE
Nanosaur and Nanosaur Extreme as 2 different games

### ISSUE THREAD

**Issue by Catarax** [jorio/Nanosaur#34]
When changing the difficulty, even if the game is on another folder, the difficulty is sync.

I would like to have 2 separate games for Nanosaur since Extreme was available as a second app on Pangea Software website.

Maybe having a new Dinosaur running on the dashboard with the extreme logo would be great also.

**Comment by jorio** [comment]
“Extreme” is essentially an extra difficulty level for the same game. I believe Pangea spun off Extreme into a separate product to encourage people to purchase the game (Nanosaur was freeware initially).

I merged the two difficulty levels into one game because that streamlines maintenance for me. I'm not keen on doubling the amount of apps I have to release and take care of across all platforms for pretty much the same game.

Hope you understand!
