### ISSUE TITLE
Very poor performance on Apple Silicon

### ISSUE THREAD

**Issue by orazioedoardo** [jorio/Nanosaur#8]
I'm experiencing very low frame rate and lag spikes when running on Apple Silicon Mac (native build). Mostly occurs when flying in areas with lots of objects on screen, like the jungle area or when an enemy dinosaur turns into pieces when killed.

I do not know the exact frame rate but I estimate between 5 and 10 fps in those circumstances. Extreme version is almost unplayable, Normal is better because less dinosaurs.

Information provided in settings:

> Renderer: Apple M1
> OpenGL: 4.1 Metal - 71.0.7
> GLSL: 4.10
> Game version: 1.4.1

Intel version under Rosetta has the same issues. Looking at activity monitor I see that Nanosaur uses 35% to 45% CPU and 70% to 90% GPU. I've noticed that if I open the game, wait a while on the main "spinning" menu, and then start a new game, then I get basically 1 fps and I can't even leave the game without force quit.

When running from Terminal the following warning is reported:

```
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
```

Is there anything I can do to help track down the issue?

**Comment by jorio** [comment]
Thank you for reporting this.

@orazioedoardo, can you try to switch to branch "[noquesa](https://github.com/jorio/Nanosaur/tree/noquesa)", recompile the game and see if it's smoother? I don't have M1 hardware so I can't test this myself. 

That branch is an attempt at making a tailor-made renderer for the game, instead of using Quesa. It's very much a work in progress, so some elements will look incorrect. Note that all 2D elements are missing for now (including the HUD, win/lose FMVs, and the setting screen). Hopefully though, the performance might be improved. Let me know!

**Comment by orazioedoardo** [comment]
Performance wise, it works much better with the `noquesa` branch, I'm averaging between 15 to 20% CPU and 15% GPU now. I've also tried a "stress test" by hacking the `src/Glue/ProMode.c` file to increase the viewing distance by 5 and number of enemies by 10 and still holds well.

I had to run `git submodule update --recursive --remote` from within the Nanousaur repo to switch to the latest Pomme commit, otherwise `git clone --recurse-submodules ...` would pull [this](https://github.com/jorio/Pomme/tree/833dab9a85008ec86f6e26fe268a243a55548283) older commit and the game wouldn't build.

By the way those performance issues also applied to Budgom from a quick test.

**Comment by jorio** [comment]
Awesome, thank you. I'll finish the new renderer for Nanosaur and see if I can port it to Bugdom afterwards.

**Comment by orazioedoardo** [comment]
Do you have an idea on what could cause such issues with the Apple GPU? I've found [this](https://developer.apple.com/documentation/metal/gpu_features/understanding_gpu_family_4) about a different rendering mode:

> TBDR makes some significant changes to the IM architecture, processing the scene after all of the primitives have been submitted. The screen is split into tiles that are processed separately. All geometry that intersects a tile is processed simultaneously, and occluded fragments are discarded before the rasterization and fragment shading stages. A tile is rendered into fast local memory on the GPU and is written out to device memory only after rendering completes.

**Comment by jorio** [comment]
I'm not quite sure what was going on with the game on that hardware combination specifically. We'd have to profile Nanosaur 1.4.1 (the last version that uses Quesa for rendering) on M1 to find out where the bottleneck lies.

That being said, even before Apple Silicon, I wasn't super happy with the game's performance on low-end PCs. There was a lot of overhead incurred by transparent meshes and the creation of small objects such as particles — but at least the game was playable. So, Nanosaur being unplayable on M1 was the push I needed to rewrite the game's 3D code in order to have more control over the rendering.

@orazioedoardo, can you confirm that [version 1.4.2](https://github.com/jorio/Nanosaur/releases/tag/v1.4.2) runs acceptably on M1? If it does, we can close this issue ;)

**Comment by orazioedoardo** [comment]
> @orazioedoardo, can you confirm that [version 1.4.2](https://github.com/jorio/Nanosaur/releases/tag/v1.4.2) runs acceptably on M1? If it does, we can close this issue ;)

It runs very well! I'm consistently getting between 100 and 120 FPS playing Extreme! mode with V-Sync off. By the way thank you very much for this port, It's kinda amazing that I'm able to play this game from the Classic era on a modern Mac without any emulators or VM.
